services:
  - type: web
    name: telegram-multi-bot-platform
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false
      - key: CARD_NUMBER
        sync: false
      - key: CARD_OWNER
        sync: false
